import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

type Store={id:string;name:string;document:string;phone:string;address:string;zip:string|null;city:string|null;state:string|null;status:string;is_open:boolean;commission_bps:number;fee_bps:number;terms_version:number;accepted_terms_version:number;delivery_mode:string;own_driver_available:boolean};
type Inv={store_id:string;on_hand:number;reserved:number};
export default function PartnersManager(){
 const [stores,setStores]=useState<Store[]>([]); const [inv,setInv]=useState<Inv[]>([]); const [saving,setSaving]=useState<string|null>(null);
 const load=async()=>{const [{data:s,error},{data:i}]=await Promise.all([supabase.from("partner_stores" as never).select("id,name,document,phone,address,zip,city,state,status,is_open,commission_bps,fee_bps,terms_version,accepted_terms_version,delivery_mode,own_driver_available").order("created_at",{ascending:false}),supabase.from("partner_inventory" as never).select("store_id,on_hand,reserved")]);if(error)return toast.error("Não foi possível carregar os revendedores.");setStores((s??[]) as unknown as Store[]);setInv((i??[]) as unknown as Inv[]);};
 useEffect(()=>{void load()},[]);
 const save=async(s:Store)=>{if(s.commission_bps<0||s.commission_bps>10000||s.fee_bps<0||s.fee_bps>10000||s.commission_bps+s.fee_bps>10000)return toast.error("Comissão e taxa precisam somar no máximo 100%.");setSaving(s.id);const {error}=await supabase.rpc("partner_command" as never,{p_action:"admin_store",p_payload:{store_id:s.id,status:s.status,commission_bps:s.commission_bps,fee_bps:s.fee_bps}} as never);setSaving(null);if(error)return toast.error(error.message);toast.success("Cadastro do revendedor atualizado. A loja permanece fechada até o aceite das condições.");await load();};
 return <div className="space-y-4"><div><h2 className="text-xl font-semibold">Revendedores</h2><p className="text-sm text-muted-foreground">Aprove cadastros e defina as condições comerciais. Aprovar não abre a loja automaticamente.</p></div>{stores.length===0?<Card className="p-8 text-center text-sm text-muted-foreground">Nenhum revendedor cadastrado.</Card>:stores.map(s=>{const rows=inv.filter(i=>i.store_id===s.id),available=rows.reduce((n,i)=>n+Math.max(0,Number(i.on_hand)-Number(i.reserved)),0),termsOk=s.accepted_terms_version===s.terms_version;return <Card key={s.id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-lg">{s.name}</CardTitle><div className="flex gap-2"><Badge variant="outline">{s.status}</Badge><Badge variant={termsOk?"secondary":"destructive"}>{termsOk?"Termos aceitos":"Aceite pendente"}</Badge><Badge variant={available>0?"secondary":"outline"}>{available} un. disponíveis</Badge></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 text-sm md:grid-cols-2"><p><strong>CNPJ:</strong> {s.document}</p><p><strong>Contato:</strong> {s.phone}</p><p className="md:col-span-2"><strong>Endereço:</strong> {s.address} · {s.city}/{s.state} · {s.zip}</p><p><strong>Entrega:</strong> {s.delivery_mode}{s.own_driver_available?" · próprio disponível":""}</p><p><strong>Operação:</strong> {s.is_open?"aberta":"fechada"}</p></div><div className="grid gap-3 md:grid-cols-3"><div><Label>Status</Label><Select value={s.status} onValueChange={v=>setStores(x=>x.map(y=>y.id===s.id?{...y,status:v}:y))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pending">Pendente</SelectItem><SelectItem value="approved">Aprovado</SelectItem><SelectItem value="rejected">Reprovado</SelectItem><SelectItem value="suspended">Suspenso</SelectItem></SelectContent></Select></div><div><Label>Comissão (%)</Label><Input type="number" min="0" max="100" step="0.01" value={s.commission_bps/100} onChange={e=>setStores(x=>x.map(y=>y.id===s.id?{...y,commission_bps:Math.round(Number(e.target.value)*100)}:y))}/></div><div><Label>Taxa plataforma (%)</Label><Input type="number" min="0" max="100" step="0.01" value={s.fee_bps/100} onChange={e=>setStores(x=>x.map(y=>y.id===s.id?{...y,fee_bps:Math.round(Number(e.target.value)*100)}:y))}/></div></div><Button disabled={saving===s.id} onClick={()=>void save(s)}>{saving===s.id?"Salvando...":"Salvar aprovação e condições"}</Button></CardContent></Card>})}</div>;
}