import {useCallback,useEffect,useState} from "react";
import {supabase} from "@/integrations/supabase/client";
import {Button} from "@/components/ui/button";
import {toast} from "sonner";

type Item={id:string;store_id:string;name:string;price:number;quantity:number;image_url:string|null;active:boolean};
export default function PartnerOwnProducts({storeId}:{storeId:string}){
 const [items,setItems]=useState<Item[]>([]);
 const [name,setName]=useState("");const [price,setPrice]=useState("");const [quantity,setQuantity]=useState("0");const [image,setImage]=useState("");const [busy,setBusy]=useState(false);const [savingId,setSavingId]=useState<string|null>(null);
 const load=useCallback(async()=>{const {data,error}=await supabase.from("partner_store_products" as never).select("id,store_id,name,price,quantity,image_url,active").eq("store_id",storeId).order("created_at",{ascending:false});if(error)toast.error(error.message);else setItems((data??[]) as unknown as Item[]);},[storeId]);
 useEffect(()=>{void load();},[load]);
 const add=async()=>{const p=Number(price),q=Number(quantity);if((image.trim()&&!/^https:\/\//i.test(image.trim()))||name.trim().length<2||name.trim().length>150||price.trim()===""||!Number.isFinite(p)||p<=0||!Number.isInteger(q)||q<0)return toast.error("Informe nome, preço e quantidade válidos.");setBusy(true);const {error}=await supabase.from("partner_store_products" as never).insert({store_id:storeId,name:name.trim(),price:p,quantity:q,image_url:image.trim()||null} as never);setBusy(false);if(error)return toast.error(error.message);setName("");setPrice("");setQuantity("0");setImage("");toast.success("Produto cadastrado na sua loja.");await load();};
 const save=async(item:Item,changes:Partial<Item>)=>{if(savingId)return;setSavingId(item.id);try{const {error}=await supabase.from("partner_store_products" as never).update(changes as never).eq("id",item.id).eq("store_id",storeId);if(error)toast.error(error.message);else{toast.success("Produto atualizado.");await load();}}finally{setSavingId(null);}};
 return <section className="mt-5 space-y-3 rounded-xl border border-[#d4af37]/30 p-4"><h3 className="font-bold text-yellow-200">Produtos exclusivos da minha loja</h3><p className="text-xs text-zinc-400">Cadastro individual. Produtos de outras lojas não podem ser alterados aqui. O checkout desses produtos ainda está em integração.</p>
 <div className="grid gap-2 sm:grid-cols-2"><input className="rounded-lg border bg-black/30 p-2" placeholder="Nome do produto" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-lg border bg-black/30 p-2" placeholder="Preço R$" type="number" min="0" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/><input className="rounded-lg border bg-black/30 p-2" placeholder="Quantidade" type="number" min="0" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/><input className="rounded-lg border bg-black/30 p-2" placeholder="URL da foto (opcional)" value={image} onChange={e=>setImage(e.target.value)}/></div><Button disabled={busy} onClick={()=>void add()}>Cadastrar produto</Button>
 {items.map(item=><div key={item.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-white/10 p-3"><div className="min-w-[120px] flex-1"><strong>{item.name}</strong><p className="text-xs text-zinc-400">R$ {Number(item.price).toFixed(2)} · {item.quantity} un.</p></div><Button disabled={savingId!==null} size="sm" variant="outline" onClick={()=>{const value=window.prompt("Novo nome",item.name);if(value===null)return;if(value.trim().length<2||value.trim().length>150)return toast.error("Nome inválido");void save(item,{name:value.trim()});}}>Nome</Button><Button size="sm" variant="outline" onClick={()=>{const value=window.prompt("Nova quantidade",String(item.quantity));if(value===null)return;const q=Number(value);if(!Number.isInteger(q)||q<0)return toast.error("Quantidade inválida");void save(item,{quantity:q});}}>Quantidade</Button><Button size="sm" variant="outline" onClick={()=>{const value=window.prompt("Novo preço",String(item.price));if(value===null)return;const p=Number(value);if(value.trim()===""||!Number.isFinite(p)||p<=0)return toast.error("Preço inválido");void save(item,{price:p});}}>Preço</Button><Button size="sm" variant="outline" onClick={()=>{const value=window.prompt("URL da foto (deixe vazio para remover)",item.image_url??"");if(value===null)return;const url=value.trim();if(url&&!/^https:\/\//i.test(url))return toast.error("Use uma URL HTTPS para a foto");void save(item,{image_url:url||null});}}>Foto</Button><Button size="sm" variant="outline" onClick={()=>void save(item,{active:!item.active})}>{item.active?"Desativar":"Ativar"}</Button></div>)}</section>;
}
