// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os produtos ativos do cat\xE1logo da Loja Fam\xEDlia Maromba, opcionalmente filtrados por categoria (suplementos, roupas, acessorios, equipamento, cimed, mansao).",
  inputSchema: {
    category: z.string().optional().describe("Categoria opcional (ex: suplementos, roupas, acessorios, equipamento)."),
    limit: z.number().int().min(1).max(100).optional().describe("Quantidade m\xE1xima de itens (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("products").select("id,name,category,price,min_qty,badge,image_url,is_active").eq("is_active", true).order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_order_default = defineTool2({
  name: "get_order",
  title: "Consultar pedido",
  description: "Consulta os detalhes e o status de um pedido pelo seu c\xF3digo (ex: FM-XXXXXX).",
  inputSchema: {
    order_code: z2.string().min(3).describe("C\xF3digo do pedido, como aparece no recibo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_code }, ctx) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.rpc("get_order_by_code", { _order_code: order_code });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const order = Array.isArray(data) ? data[0] : data;
    if (!order) return { content: [{ type: "text", text: `Pedido ${order_code} n\xE3o encontrado.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(order) }],
      structuredContent: { order }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "Meus pedidos",
  description: "Lista os pedidos do usu\xE1rio autenticado.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: { user }, error: authError } = await supabase.auth.getUser(ctx.getToken());
    if (authError || !user) {
      return { content: [{ type: "text", text: "Sess\xE3o inv\xE1lida." }], isError: true };
    }
    const { data, error } = await supabase.from("orders").select("order_code,total_amount,payment_method,payment_status,delivery_status,tracking_code,created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "knoypszawytcyjcuheor";
var mcp_default = defineMcp({
  name: "familia-maromba-mcp",
  title: "Loja Oficial Fam\xEDlia Maromba",
  version: "0.1.0",
  instructions: "Ferramentas do portal de atacado Fam\xEDlia Maromba. Use `list_products` para navegar no cat\xE1logo, `get_order` para consultar um pedido pelo c\xF3digo e `list_my_orders` para ver os pedidos do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_order_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
