// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Public project settings are fixed here because the Lovable host can override
// VITE_ environment variables during its build.
const SUPABASE_URL = 'https://svkatjljeyyuobayjqjv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_dmkRPGZLTcAYzZOsxZgBpQ_IMQ08iOU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});